val:
  _target_: src.datasets.CustomDatasetAudioOnly
  mix_audio_dir: "/Users/legend/Desktop/Универ/4/DLA/hw2/dla_dataset/audio/val/mix"
  s1_audio_dir: "/Users/legend/Desktop/Универ/4/DLA/hw2/dla_dataset/audio/val/s1"
  s2_audio_dir: "/Users/legend/Desktop/Универ/4/DLA/hw2/dla_dataset/audio/val/s2"
  instance_transforms: ${transforms.instance_transforms.inference}