train:
  _target_: src.datasets.CustomDatasetAudioOnly
  mix_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/mix"
  s1_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/s1"
  s2_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/s2"
  limit: 3
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.CustomDatasetAudioOnly
  mix_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/mix"
  s1_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/s1"
  s2_audio_dir: "/home/andrewut/dla/dla_dataset/audio/train/s2"
  limit: 3
  instance_transforms: ${transforms.instance_transforms.inference}